version: "3"

services:
  postgres:
    image: postgres:13.2
    volumes:
      - ./book-service-impl/src/test/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin